CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    IsActive BIT NOT NULL DEFAULT 1
)

CREATE TABLE Accounts
(
AccountID INT PRIMARY KEY IDENTITY(1, 1),
AccountNumber NVARCHAR(22) NOT NULL UNIQUE,
AvailableAmount DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
IsActive BIT DEFAULT 1,
)

CREATE TABLE UserAccounts
(
UserID INT NOT NULL,
AccountID INT NOT NULL,
PRIMARY KEY(UserID, AccountID),
FOREIGN KEY (UserID) REFERENCES Users(UserID),
FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID),
)


CREATE TABLE Payments
(
PaymentID INT PRIMARY KEY IDENTITY(1, 1),
FromAccountId INT NOT NULL,
ToAccountNumber NVARCHAR(22) NOT NULL,
Amount DECIMAL(18, 2) NOT NULL,
Reason NVARCHAR(32) NOT NULL,
Status NVARCHAR(20) NOT NULL DEFAULT 'ИЗЧАКВА',
CreatedDate DATETIME2 DEFAULT GETDATE(),
ProcessedDate DATETIME2,
CreatedByUserId INT NOT NULL,
FOREIGN KEY (FromAccountId) REFERENCES Accounts(AccountId),
FOREIGN KEY (CreatedByUserId) REFERENCES Users(UserId)
)